import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Local Font
const orbitron = localFont({
  src: "/fonts/Orbitron-Regular.ttf", 
  variable: "--font-orbitron",
});

const grotesk = localFont({
  src: "/fonts/SpaceGrotesk-Regular.ttf",
  variable: "--font-grotesk",
});

const tektur = localFont({
  src:"/fonts/Tektur-Bold.ttf",
  variable: "--font-Tektur",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${grotesk.variable} ${tektur.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
